import Layout from "./layout"
import Hero from "./Hero"
import About from "./About"
import Projects from "./Projects"
import Survey from "./Survey"
import Customers from "./Customers"
import WhoWeAre from "./WhoWeAre"
//import Algolia from "./Algolia"
import GridProjects from "./GridProjects"
export { Layout, Hero, About, Projects, Survey, GridProjects, WhoWeAre,Customers }
